version: "3.8"

services:
  db:
    image: arangodb
    volumes:
      - ${ARANGODB_DATABASE_PATH}:/var/lib/arangodb3
      - ${ARANGODB_DATABASE_APPS_PATH}:/var/lib/arangodb3-apps
    environment:
      - ARANGO_ROOT_PASSWORD=${ARANGODB_ROOT_PASSWORD}
    ports:
      - "8529:8529"
    networks:
      gmi-net:
        aliases:
          - db

  scripts:
    image: gmi-scripts:latest
    depends_on:
      - db
    environment:
      - CONFIG_PATH=/usr/src/gmi/config.toml
    volumes:
      - ${CONFIG_TOML_PATH}:/usr/src/gmi/config.toml
    networks:
      gmi-net:
        aliases:
          - scripts
    command: "app reset_db"

networks:
  gmi-net:
