version: "3.8"

services:
  db:
    image: arangodb
    volumes:
      - ${ARANGODB_DATABASE_PATH}:/var/lib/arangodb3
      - ${ARANGODB_DATABASE_APPS_PATH}:/var/lib/arangodb3-apps
    environment:
      - ARANGO_ROOT_PASSWORD=${ARANGODB_ROOT_PASSWORD}
    ports:
      - "8529:8529"
    networks:
      gmi-net:
        aliases:
          - db

networks:
  gmi-net:
